# Generated by Django 3.2 on 2022-03-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_categories',
            field=models.CharField(choices=[('Products', 'Products'), ('Website', 'Website'), ('Profile', 'Profile'), ('Delivery', 'Delivery'), ('Checkout', 'Checkout')], default='Products', max_length=70),
        ),
    ]
